import { GlobalContextProvider } from "../context/user";

import "./globals.css";

import { Roboto_Mono } from "next/font/google";

const mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mono.className} bg-slate-900 text-white container`}>
        <GlobalContextProvider>{children}</GlobalContextProvider>
      </body>
    </html>
  );
}
