"use client";
import { useEffect, useState } from "react";
import "./globals.css";
import { Roboto_Mono } from "next/font/google";
const mono = Roboto_Mono({ subsets: ["latin"] });
import Loading from "./loader";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    const token = localStorage.getItem("token");

    if (token) {
      fetch(`/api/users/@me`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
        method: "POST",
      })
        .then((response) => response.json())
        .then((data) => {
          console.log(data);
          // setUserData(data);
          setLoading(false);
        })
        .catch((error) => {
          console.error("Error fetching user data:", error);
          setLoading(false);
        });
    } else {
      setLoading(false);
    }
  }, []);

  if (loading) {
    return <Loading />;
  }

  return (
    <html lang="en">
      <body className={`${mono.className} bg-slate-900 text-white container`}>
        {children}
      </body>
    </html>
  );
}
