"use client";
import "./globals.css";
import { Roboto_Mono } from "next/font/google";
import { createContext, useState, useEffect } from "react";
import { users_discord_info_obj } from "@/utils/types";
import Loading from "./loader";

const mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const UserContext = createContext<users_discord_info_obj | null>(null);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [userData, setUserData] = useState<users_discord_info_obj | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = localStorage.getItem("token");

    if (token) {
      fetch(`api//users/@me`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
        method: "POST",
      })
        .then((response) => response.json())
        .then((data) => {
          setUserData(data);
          setLoading(false);
        })
        .catch((error) => {
          console.error("Error fetching user data:", error);
          setLoading(false);
        });
    } else setLoading(false);
  }, []);

  if (loading) {
    return <Loading></Loading>;
  }

  return (
    <UserContext.Provider value={userData}>
      <html lang="en">
        <body className={`${mono.className} bg-slate-900 text-white container`}>
          {children}
        </body>
      </html>
    </UserContext.Provider>
  );
}
